TicketSystem.WebApp/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TicketSystem.BusinessLayer;
using TicketSystem.BusinessLayer.Result;
using TicketSystem.Entities;
using TicketSystem.WebApp.Filters;
using TicketSystem.WebApp.Models;

namespace TicketSystem.WebApp.Controllers
{
    public class TicketController : Controller
    {
        TicketManager ticketManager = new TicketManager();
        // GET: Ticket
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(Ticket ticket, HttpPostedFileBase ticketImg)
        {
            ModelState.Remove("Owner");
            if (ModelState.IsValid)
            {
                if (ticketImg != null && (ticketImg.ContentType == "image/jpeg" || ticketImg.ContentType == "image/jpg" || ticketImg.ContentType == "image/png"))
                {
                    string filename = $"ticket_{ticket.Id}.{ticketImg.ContentType.Split('/')[1]}";
                    ticketImg.SaveAs(Server.MapPath($"~/Images/{filename}"));
                    ticket.Img = filename;
                }
                ticket.Owner = CurrentSession.user;
                ticket.IsSolved = true;
                ticketManager.Insert(ticket);

                return RedirectToAction("Index","Home");
            }
            return View(ticket);
        }

        [Auth]
        public ActionResult GetTicketsById(int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<Ticket> list = ticketManager.ListQueryable().Where(x => x.Owner.Id == id).ToList();
            
            if(list==null)
            {
                return HttpNotFound();
            }

            return PartialView("_PartialTickets", list);
        }

        public ActionResult GetDetailsById(int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ticket ticket = ticketManager.Find(x => x.Id == id);
            if(ticket==null)
            {
                return HttpNotFound();
            }
            return PartialView("_PartialTicketDetail",ticket);
        }

        public ActionResult IsSolved(int? id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadGateway);
            }
            Ticket ticket = ticketManager.Find(x => x.Id == id);
            if(ticket==null)
            {
                return HttpNotFound();
            }
            return PartialView("_PartialSolvedButton",ticket);
        }

        [Auth]
        [HttpPost]
        public ActionResult Solving(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadGateway);
            }
            Ticket ticket = ticketManager.Find(x => x.Id == id);
            if (ticket == null)
            {
                return HttpNotFound();
            }

            ticket.IsSolved = !ticket.IsSolved;
            int result = ticketManager.Update(ticket);

            if (result > 0)
                return PartialView("_PartialSolvedButton", ticket);

            return View();
        }
    }
}

TicketSystem.WebApp/Views/Ticket/Create.cshtml
@using TicketSystem.Entities
@model Ticket
@{
    ViewBag.Title = "Create";
}
<br /><br />
<div class="container">
    <div class="col-md-4 col-md-offset-4 text-center">
        <strong class="">Create New Ticket</strong>
        <hr />
    </div>
    @using (Html.BeginForm("Create", "Ticket", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(false)
        <div class="row">
            <div class="col-md-5 col-md-push-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.TextBoxFor(Model => Model.Title, new { @class = "form-control", placeholder = "Title" })
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.TextAreaFor(Model => Model.Text,5,30, new { @class = "form-control", placeholder = "Description" })
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(model => model.Img, htmlAttributes: new { @class = "control-label col-md-2" })
                    <input type="file" name="ticketImg" id="ticketImg" class="form-control" /><br />
                    <p class="small text-center"><span class="glyphicon glyphicon-info-sign"></span>&nbsp;Please use a JPG, JPEG or PNG. (max 5mb)</p>
                </div>
                <br />
                <button class="btn btn-success center-block" type="submit"><span class="glyphicon glyphicon-send"></span> Send</button>
            </div>
        </div>
    }
    
</div>